### ISSUE TITLE
Does it have support for the non-bcp47 formatted locale?

### ISSUE THREAD

**Issue by ohpyupi** [krakenjs/makara-languagepackpath#4]
I do need to have pass non-bcp47 formatted locale to the module. But it throws an error saying invalid locale. Is there any workaround over it?

**Comment by aredridel** [comment]
It doesn't — it would require the code to be modified. What are you actually doing?

**Comment by ohpyupi** [comment]
I am working on dust/makara upgrade for my application, but I am stuck with non-bcp47 formatted locales. For example, in our app, we have made group locales that include multiple countries. But since that group locale does not follow the bcp format, it throws an error. Hopefully for the server-side rendering there was a workaround https://github.com/krakenjs/dust-makara-helpers/pull/15/files#diff-168726dbe96b3ce427e7fedce31bb0bcR28. But since the languagepack does not allow non-bcp format locale, it throws an error on client-side rendering. I do need an overriding logic in this module like the one in the dust-makara-helper. I can raise a PR if that is possible. Please let me know.

**Comment by ohpyupi** [comment]
Maybe we can allow passing an alternative function that replaces `languagePackPath` through the options parameter. That way we can bypass the bcp47 format check.
```js
res.locals.makara.languagePackPath = options.languagePackPath 
  ? options.languagePackPath(res.locals[localeContext], nosuffix)
  : languagePackPath(res.locals[localeContext], nosuffix);
```

**Comment by ohpyupi** [comment]
Okay. I found a workaround. Basically, if I pass non-string locale object and follow a certain structure, it would not require the locale to be parsed by bcp module. Thanks!
